{
  "delete": {
     "employeeId":1
  } 
}

mutation DeleteEmployee($delete: EmployeeDeleteInput!) {
  deleteEmployee(delete: $delete) {
    ... on IEmployee {
      id
      name
      department
      status
    }
    ... on FullTimeEmployeeType {
      salary
      type
    }
    ... on PartTimeEmployeeType {
      hourlyRate
      type
    }
  }
}
