{
  "create": {
    "partTimeEmployeeInput": {
    "id":7,
    "name": "Sachin",
    "department": "IT",
    "hourlyRate": 7000,
    "status": "ACTIVE",
    "type": "FULL_TIME"
    }
  }
}


mutation AddEmployee($create: EmployeeInput!) {
  addEmployee(create: $create) {
    ... on IEmployee {
      id
      name
      department
      status
    }
    ... on FullTimeEmployeeType {
      salary
      type
    }
    ... on PartTimeEmployeeType {
      hourlyRate
      type
    }
  }
}
