{
  "input": {
    "id":6,
    "name": "Sam",
    "department": "IT",
    "salary": 6000,
    "status": "ACTIVE",
    "type": "FULL_TIME"
  }
}

mutation AddEmployee($input: EmployeeInput!) {
  addEmployee(input: $input) {
    ... on IEmployee {
      id
      name
      department
      status
    }
    ... on FullTimeEmployeeType {
      salary
      type
    }
    ... on PartTimeEmployeeType {
      hourlyRate
      type
    }
  }
}
