{
  "update": {
    "fullTimeEmployeeInput": {
        "id": 3,
        "name": "Pahal update",
        "department": "IT",
        "status": "ACTIVE",
        "salary": 3000,
        "type": "FULL_TIME"
    }
  }
}

mutation UpdateEmployee($update: EmployeeUpdateInput!) {
  updateEmployee(update: $update) {
    ... on IEmployee {
      id
      name
      department
      status
    }
    ... on FullTimeEmployeeType {
      salary
      type
    }
    ... on PartTimeEmployeeType {
      hourlyRate
      type
    }
  }
}
